# To use:
#
#     prek run -a
#
# Or:
#
#     prek install --prepare-hooks -f  # (runs every time you commit in git)
#
# To update this file:
#
#     prek autoupdate
#
# See https://prek.j178.dev/

repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        exclude: (^bun\.lock$|/_generated/)
        exclude_types: [svg]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.0
    hooks:
      - id: check-github-actions
        args: ['--verbose']
      - id: check-github-workflows
        args: ['--verbose']

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        language: system
        entry: cargo fmt
        pass_filenames: false

      - id: cargo-check
        name: cargo-check
        language: system
        entry: cargo check
        pass_filenames: false

      - id: commitlint
        name: commitlint
        language: system
        entry: commitlint --edit
        stages: [commit-msg]

      - id: eslint
        name: eslint
        language: system
        entry: bun turbo run lint
        pass_filenames: false

      - id: oxlint
        name: oxlint
        language: system
        entry: bun run lint:oxlint
        pass_filenames: false

      - id: svelte-check
        name: svelte-check
        language: system
        entry: bun turbo run check
        pass_filenames: false

      - id: prettier
        name: prettier
        language: system
        entry: bun prettier --write .
        pass_filenames: false

      - id: mermaid
        name: mermaid
        language: system
        entry: bun run lint:mermaid
        pass_filenames: false
