#[path = "src/skill_limits.rs"]
mod skill_limits;
#[path = "src/skill_name.rs"]
mod skill_name;

use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use skill_limits::MAX_SKILL_CONTENT_BYTES;
use skill_name::validate_skill_name;

const AUTHORED_SKILLS_DIR: &str = "skills";
const VENDORED_SKILLS_DIR: &str = ".agents/skills";

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let mut seen_names: HashSet<String> = HashSet::new();
    let mut embedded: Vec<(String, PathBuf)> = Vec::new();

    for tier in [AUTHORED_SKILLS_DIR, VENDORED_SKILLS_DIR] {
        let skills_dir = manifest_dir.join(tier);
        println!("cargo:rerun-if-changed={}", skills_dir.display());
        if !skills_dir.is_dir() {
            continue;
        }

        let mut dirs: Vec<PathBuf> = fs::read_dir(&skills_dir)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", skills_dir.display()))
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|path| path.is_dir())
            .collect();
        dirs.sort();

        for skill_dir in dirs {
            let name = skill_dir
                .file_name()
                .and_then(|value| value.to_str())
                .unwrap_or_else(|| {
                    panic!(
                        "built-in skill directory name is not valid UTF-8: {}",
                        skill_dir.display()
                    )
                })
                .to_string();

            validate_skill_name(&name).unwrap_or_else(|error| {
                panic!(
                    "invalid built-in skill directory '{}': {error}",
                    skill_dir.display()
                )
            });

            if !seen_names.insert(name.clone()) {
                panic!(
                    "built-in skill '{name}' exists in both {AUTHORED_SKILLS_DIR}/ and {VENDORED_SKILLS_DIR}/; remove one"
                );
            }

            let skill_md = skill_dir.join("SKILL.md");
            println!("cargo:rerun-if-changed={}", skill_dir.display());
            println!("cargo:rerun-if-changed={}", skill_md.display());

            if !skill_md.is_file() {
                panic!(
                    "built-in skill '{name}' is missing SKILL.md (expected {})",
                    skill_md.display()
                );
            }

            // Embedded skills have no on-disk directory at runtime, so anything
            // beyond SKILL.md would be silently dropped by read_skill.
            let entries: Vec<_> = fs::read_dir(&skill_dir)
                .unwrap_or_else(|error| panic!("failed to read {}: {error}", skill_dir.display()))
                .collect::<Result<_, _>>()
                .unwrap_or_else(|error| {
                    panic!("failed to read entry in {}: {error}", skill_dir.display())
                });
            for entry in entries {
                let is_skill_md = entry.file_name() == "SKILL.md"
                    && entry
                        .file_type()
                        .map(|kind| kind.is_file())
                        .unwrap_or(false);
                if !is_skill_md {
                    panic!(
                        "built-in skill '{name}' contains '{}'; built-in skills may only contain SKILL.md",
                        entry.file_name().to_string_lossy()
                    );
                }
            }

            let skill_md_size = fs::metadata(&skill_md)
                .unwrap_or_else(|error| panic!("failed to stat {}: {error}", skill_md.display()))
                .len();
            if skill_md_size > MAX_SKILL_CONTENT_BYTES as u64 {
                panic!(
                    "built-in skill '{name}' is {skill_md_size} bytes; SKILL.md must fit the {MAX_SKILL_CONTENT_BYTES}-byte read_skill cap"
                );
            }

            embedded.push((name, skill_md));
        }
    }

    let mut generated = String::from(
        "// @generated by build.rs from skills/*/SKILL.md and .agents/skills/*/SKILL.md. Do not edit.\n\
         pub const BUILTIN_SKILLS: &[(&str, &str)] = &[\n",
    );
    for (name, skill_md) in &embedded {
        let relative = skill_md
            .strip_prefix(&manifest_dir)
            .expect("skill file lives under the crate")
            .to_string_lossy()
            .replace('\\', "/");
        generated.push_str(&format!(
            "    (\n        {name:?},\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{relative}\")),\n    ),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("builtin_skills_generated.rs");
    write_if_changed(&dest, &generated);
}

fn write_if_changed(path: &Path, contents: &str) {
    let previous = fs::read_to_string(path).ok();
    if previous.as_deref() == Some(contents) {
        return;
    }
    fs::write(path, contents)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", path.display()));
}
