#[path = "src/skill_name.rs"]
mod skill_name;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use skill_name::validate_skill_name;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let skills_dir = manifest_dir.join("skills");
    println!("cargo:rerun-if-changed={}", skills_dir.display());

    let mut skill_names = Vec::new();
    if skills_dir.is_dir() {
        let mut dirs: Vec<PathBuf> = fs::read_dir(&skills_dir)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", skills_dir.display()))
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|path| path.is_dir())
            .collect();
        dirs.sort();

        for skill_dir in dirs {
            let name = skill_dir
                .file_name()
                .and_then(|value| value.to_str())
                .unwrap_or_else(|| {
                    panic!(
                        "built-in skill directory name is not valid UTF-8: {}",
                        skill_dir.display()
                    )
                })
                .to_string();

            validate_skill_name(&name).unwrap_or_else(|error| {
                panic!(
                    "invalid built-in skill directory '{}': {error}",
                    skill_dir.display()
                )
            });

            let skill_md = skill_dir.join("SKILL.md");
            println!("cargo:rerun-if-changed={}", skill_dir.display());
            println!("cargo:rerun-if-changed={}", skill_md.display());

            if !skill_md.is_file() {
                panic!(
                    "built-in skill '{name}' is missing SKILL.md (expected {})",
                    skill_md.display()
                );
            }

            skill_names.push(name);
        }
    }

    let mut generated = String::from(
        "// @generated by build.rs from skills/*/SKILL.md. Do not edit.\n\
         pub const BUILTIN_SKILLS: &[(&str, &str)] = &[\n",
    );
    for name in &skill_names {
        generated.push_str(&format!(
            "    (\n        {name:?},\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/skills/{name}/SKILL.md\")),\n    ),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("builtin_skills_generated.rs");
    write_if_changed(&dest, &generated);
}

fn write_if_changed(path: &Path, contents: &str) {
    let previous = fs::read_to_string(path).ok();
    if previous.as_deref() == Some(contents) {
        return;
    }
    fs::write(path, contents)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", path.display()));
}
