[package]
name = "sprocket-cli"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "sprocket"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive", "env"] }
hmac = "0.13.0"
open = "5.3.3"
reqwest = { version = "0.13.4", default-features = false, features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.11.0"
sprocket-server = { path = "../sprocket-server" }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
uuid = { version = "1.21.0", features = ["v4"] }
