[package]
name = "sprocket-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sprocket"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive", "env"] }
open = "5.3.3"
reqwest = { version = "0.13.4", default-features = false, features = ["json"] }
sprocket-server = { path = "../sprocket-server" }
sprocket-workspace = { path = "../sprocket-workspace" }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
uuid = { version = "1.21.0", features = ["v4"] }
