/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CommandExecOutput {
	command: string;
	cwd?: string;
	exitCode?: number;
	success: boolean;
	timedOut: boolean;
	stdout: string;
	stderr: string;
	output: string;
	truncated: boolean;
}

export declare function createFile(input: CreateFileInput): Promise<FileWriteOutput>;

export interface CreateFileInput {
	workspaceRoot: string;
	path: string;
	content: string;
}

export declare function execCommand(input: ExecCommandInput): Promise<CommandExecOutput>;

export interface ExecCommandInput {
	workspaceRoot: string;
	cmd: string;
	workdir?: string;
	shell?: string;
	login?: boolean;
	timeoutMs?: number;
	maxOutputChars?: number;
}

export interface FileEditOutput {
	path: string;
	replacements: number;
	bytesWritten: number;
}

export interface FileWriteOutput {
	path: string;
	bytesWritten: number;
}

export declare function getWorkspaceInstructions(
	workspaceRoot: string
): Array<WorkspaceInstruction>;

export declare function getWorkspaceOverview(workspaceRoot: string): WorkspaceOverview;

export declare function replaceInFile(input: ReplaceInFileInput): Promise<FileEditOutput>;

export interface ReplaceInFileInput {
	workspaceRoot: string;
	path: string;
	oldText: string;
	newText: string;
	replaceAll?: boolean;
}

export declare function runAgent(input: RunAgentRequest): Promise<void>;

export interface RunAgentRequest {
	deploymentUrl: string;
	authToken?: string;
	guestId?: string;
	runId: string;
	workspacePath: string;
}

export interface WorkspaceEntry {
	name: string;
	kind: string;
}

export interface WorkspaceInstruction {
	path: string;
	directory: string;
	contents: string;
	truncated: boolean;
}

export interface WorkspaceOverview {
	rootPath: string;
	name: string;
	gitBranch?: string;
	gitDirty: boolean;
}
