/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getWorkspaceOverview(workspaceRoot: string): WorkspaceOverview;

export declare function runAgent(input: RunAgentRequest): Promise<void>;

export interface RunAgentRequest {
	deploymentUrl: string;
	authToken?: string;
	guestId?: string;
	threadId: string;
	prompt: string;
	selectedModel: string;
	reasoningEffort: string;
	workspacePath: string;
}

export interface WorkspaceEntry {
	name: string;
	kind: string;
}

export interface WorkspaceOverview {
	rootPath: string;
	name: string;
	gitBranch?: string;
	gitDirty: boolean;
}
