/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createFile(input: CreateFileInput): Promise<FileWriteOutput>;

export interface CreateFileInput {
	workspaceRoot: string;
	path: string;
	content: string;
}

export interface FileEditOutput {
	path: string;
	replacements: number;
	bytesWritten: number;
}

export interface FileReadInput {
	workspaceRoot: string;
	path: string;
	startLine?: number;
	maxLines?: number;
}

export interface FileReadOutput {
	path: string;
	exists: boolean;
	startLine: number;
	endLine: number;
	totalLines: number;
	truncated: boolean;
	contents: string;
	error?: string;
}

export interface FileWriteOutput {
	path: string;
	bytesWritten: number;
}

export declare function getWorkspaceInstructions(
	workspaceRoot: string
): Array<WorkspaceInstruction>;

export declare function getWorkspaceOverview(workspaceRoot: string): WorkspaceOverview;

export declare function readFile(input: FileReadInput): Promise<FileReadOutput>;

export declare function replaceInFile(input: ReplaceInFileInput): Promise<FileEditOutput>;

export interface ReplaceInFileInput {
	workspaceRoot: string;
	path: string;
	oldText: string;
	newText: string;
	replaceAll?: boolean;
}

export declare function runAgent(input: RunAgentRequest): Promise<void>;

export interface RunAgentRequest {
	deploymentUrl: string;
	authToken?: string;
	guestId?: string;
	runId: string;
}

export interface WorkspaceEntry {
	name: string;
	kind: string;
}

export interface WorkspaceInstruction {
	path: string;
	directory: string;
	contents: string;
	truncated: boolean;
}

export interface WorkspaceOverview {
	rootPath: string;
	name: string;
	gitBranch?: string;
	gitDirty: boolean;
	fileCount: number;
	directoryCount: number;
	topLevelEntries: Array<WorkspaceEntry>;
	recentFiles: Array<string>;
}
