name: Prek

on:
  merge_group:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  run_prek:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: ./.github/actions/setup-nix-shell

      - uses: Swatinem/rust-cache@v2
        with:
          cmd-format: nix develop ./sprocket-shell -c {0}

      - name: Install dependencies
        shell: 'nix develop ./sprocket-shell -c bash -e {0}'
        run: bun install --frozen-lockfile

      - name: Run prek
        shell: 'nix develop ./sprocket-shell -c bash -e {0}'
        run: prek run -a

      - name: Run fmt
        shell: 'nix develop ./sprocket-shell -c bash -e {0}'
        run: nix fmt
